FROM centos:centos7.8.2003

ENV GRIDDB_SERVER_VERSION=4.5.2

# Install dependency other
RUN set -eux \
    && yum install -y wget python27 automake make gcc gcc-c++ rpm-build rsync libtool

# Install griddb server
RUN set -eux \
# Download package griddb server
    && wget -q https://github.com/griddb/griddb/releases/download/v${GRIDDB_SERVER_VERSION}/griddb-${GRIDDB_SERVER_VERSION}-linux.x86_64.rpm \
# Install package griddb server
    && rpm -ivh griddb-${GRIDDB_SERVER_VERSION}-linux.x86_64.rpm \
# Remove package
    && rm griddb-${GRIDDB_SERVER_VERSION}-linux.x86_64.rpm \
# Add repos for griddb c client
    && cd /etc/yum.repos.d/ \
    && wget https://download.opensuse.org/repositories/home:knonomura/CentOS_7/home:knonomura.repo \
# Install package griddb c client
    && yum -y install griddb-c-client \
# Remove package
    && yum clean all
