FROM ubuntu:18.04

ENV GRIDDB_SERVER_VERSION=4.5.2

# Install dependency
RUN set -eux \
    && apt-get update -y \
    && apt-get install -y gcc-4.8 g++-4.8 wget

# Create softlink gcc g++
RUn set -eux \
    && ln -sf /usr/bin/g++-4.8 /usr/bin/g++ \
    && ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc \
    && ln -sf /usr/bin/python2.7 /usr/bin/python2

# Install griddb server
RUN set -eux \
# Download package griddb server
    && wget -q https://github.com/griddb/griddb/releases/download/v${GRIDDB_SERVER_VERSION}/griddb_${GRIDDB_SERVER_VERSION}_amd64.deb \
# Install package griddb server
    && dpkg -i griddb_${GRIDDB_SERVER_VERSION}_amd64.deb \
# Clean package
    && rm griddb_${GRIDDB_SERVER_VERSION}_amd64.deb \
# Add repos for griddb c client
    && echo 'deb http://download.opensuse.org/repositories/home:/knonomura/xUbuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/home:knonomura.list \
    && curl -fsSL https://download.opensuse.org/repositories/home:knonomura/xUbuntu_18.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_knonomura.gpg > /dev/null \
    && apt update \
    && apt install griddb-c-client

# Install SWIG
RUN set -eux \
   && wget https://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz \
   && tar xvfz swig-3.0.12.tar.gz \
   && cd swig-3.0.12 \
   && ./configure \
   && make \
   && make install \
   && cd .. \
   && rm swig-3.0.12.tar.gz

# Install pyenv
RUN set -eux \
   && apt-get install -y make build-essential libssl-dev zlib1g-dev \
              libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
              libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl \
   && git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv

# Use pyenv to install python
RUN set -eux \
   && export PYENV_ROOT="$HOME/.pyenv" \
   && export PATH="$PYENV_ROOT/bin:$PATH" \
   && eval "$(pyenv init -)" \
   && pyenv install 3.6.9 \
   && pyenv global 3.6.9 \
   # Python install Numpy and Pandas
   && python -m pip install numpy pandas \
   # Update package for creating WHL package
   && python -m pip install --user --upgrade setuptools wheel

# pyenv configs
RUN set -eux \
   && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> /root/.bashrc \
   && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> /root/.bashrc \
   && echo 'if command -v pyenv 1>/dev/null 2>&1; then' >> /root/.bashrc \
   && echo '  eval "$(pyenv init -)"' >> /root/.bashrc \
   && echo 'fi' >> /root/.bashrc
# Prepare softlink to install GridDB Python Client
RUN ln -sf /root/.pyenv/versions/3.6.9/include/python3.6m/ /usr/include/python3.6

# Clean environment
RUN set -eux \
    && apt clean all
    
