FROM centos:centos7.8.2003

ENV GRIDDB_SERVER_VERSION=4.5.2

# Update system for install python2.7 and pcre
RUN set -eux \
    && yum update -y

# Install dependency other
RUN set -eux \
    && yum install -y wget python27 automake make gcc gcc-c++ rpm-build rsync libtool pcre-devel mlocate

# Install griddb server
RUN set -eux \
# Download package griddb server
    && wget -q https://github.com/griddb/griddb/releases/download/v${GRIDDB_SERVER_VERSION}/griddb-${GRIDDB_SERVER_VERSION}-linux.x86_64.rpm \
# Install package griddb server
    && rpm -ivh griddb-${GRIDDB_SERVER_VERSION}-linux.x86_64.rpm \
# Clean package
    && rm griddb-${GRIDDB_SERVER_VERSION}-linux.x86_64.rpm \
# Add repos for griddb c client
    && cd /etc/yum.repos.d/ \
    && wget https://download.opensuse.org/repositories/home:knonomura/CentOS_7/home:knonomura.repo \
# Install package griddb c client
    && yum -y install griddb-c-client

# Install SWIG
RUN set -eux \
   && wget https://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz \
   && tar xvfz swig-3.0.12.tar.gz \
   && cd swig-3.0.12 \
   && ./configure \
   && make \
   && make install \
   && cd .. \
   && rm swig-3.0.12.tar.gz


# Install pyenv
RUN set -eux \
   && yum -y install epel-release \
   && yum install -y git gcc zlib-devel bzip2-devel readline-devel sqlite-devel openssl-devel \
   && git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv

# Use pyenv to install python
RUN set -eux \
   && export PYENV_ROOT="$HOME/.pyenv" \
   && export PATH="$PYENV_ROOT/bin:$PATH" \
   && eval "$(pyenv init -)" \
   && pyenv install 3.6.4 \
   && pyenv global 3.6.4
# Python install Numpy and Pandas
   && python -m pip install numpy pandas

# Prepare softlink to install GridDB Python Client
RUN updatedb
RUN locate Python.h
RUN ln -sf /usr/include/python3.6m/ /usr/include/python3.6

# Clean environment
RUN set -eux \
    && yum clean all
    
