name: Create package on release

on: create

env:
  GRIDDB_SERVER_NAME: "griddb"
  GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
  GRIDDB_NOTIFICATION_PORT: "31999"
  GRIDDB_USERNAME: "admin"
  GRIDDB_PASSWORD: "admin"
  GRIDDB_PACKAGE_NAME: "griddb-c-client"
  GRIDDB_C_CLIENT_VERSION: ""
  GRIDDB_SERVER_VERSION: "" 

jobs:
  release_package:
    name: Create and release ${{ matrix.file_type }} file for ${{ matrix.os }}
    runs-on: macos-10.15
    strategy:
      matrix:
        include:
          - os: Ubuntu
            docker_file: .github/dockerfiles/Dockerfile-ubuntu18.04
            docker_image: ubuntu
            container_name: ubuntu_container
            package_path: dist/griddb_python-*.whl

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: docker build -t ${{ matrix.docker_image }} -f ${{ matrix.docker_file }} .
      - name: Run Docker Image
        run: docker run --name ${{ matrix.container_name }} -it -d -v `pwd`:/python_client ${{ matrix.docker_image }}
      - name: Create whl file for ${{ matrix.os }}
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec ". python_client/.github/workflows/script/function.sh \
             && build_package"
      - name: Upload whl file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.package_path }
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
