name: Create package on release

on: create

env:
  GRIDDB_SERVER_NAME: "griddb"
  GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
  GRIDDB_NOTIFICATION_PORT: "31999"
  GRIDDB_USERNAME: "admin"
  GRIDDB_PASSWORD: "admin"
  GRIDDB_PACKAGE_NAME: "griddb-c-client"
  GRIDDB_C_CLIENT_VERSION: ""
  GRIDDB_SERVER_VERSION: "" 

jobs:
  release_package:
    name: Create and release ${{ matrix.file_type }} file for ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: Centos
            file_type: rpm
            docker_file: .github/dockerfiles/Dockerfile-centos7
            docker_image: centos
            container_name: centos_container

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: docker build -t ${{ matrix.docker_image }} -f ${{ matrix.docker_file }} .
      - name: Run Docker Image
        run: docker run --name ${{ matrix.container_name }} -it -d -v `pwd`:/c_client ${{ matrix.docker_image }}
      - name: Build Griddb C Client
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec ". c_client/.github/workflows/script/function.sh \
             && build_python_client"

