name: Create package on release

on: push

env:
  GRIDDB_IMAGE: griddb/griddb
  GRIDDB_SERVER_NAME: "griddb"
  GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
  GRIDDB_NOTIFICATION_PORT: "31999"
  GRIDDB_USERNAME: "admin"
  GRIDDB_PASSWORD: "admin"
  PACKAGE_NAME: "griddb_python"

jobs:
  release_package:
    name: Create and release whl file for manylinux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Start Griddb Server
        run: docker run -t -d --network="host" --name griddb -e GRIDDB_CLUSTER_NAME=${GRIDDB_SERVER_NAME} ${GRIDDB_IMAGE}

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-4.8 g++-4.8

      - name: Install python from pyenv
        run: |
          git clone https://github.com/pyenv/pyenv.git ~/.pyenv
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init --path)"\nfi' >> ~/.bashrc
          exec "$SHELL"
          pyenv install 3.6.9
          python3 -m pip install --user --upgrade setuptools wheel
          python3 -m pip install wheel-inspect

      - name: Create whl file for manylinux
        run: . .github/workflows/script/function.sh && build_package

      - name: Check package information
        run: . .github/workflows/script/function.sh && check_package

      - name: Install package
        run: . .github/workflows/script/function.sh && install_client

      - name: Run sample
        run: . .github/workflows/script/function.sh && run_sample ${GRIDDB_NOTIFICATION_ADDRESS} ${GRIDDB_NOTIFICATION_PORT} ${GRIDDB_SERVER_NAME} ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}

      - name: Uninstall package
        run: python3 -m pip uninstall griddb-python

      - name: Upload whl file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  release_package_on_macos_10_15:
    name: Create and release whl file for MacOS 10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment for MacOS 10.15
        run: . .github/workflows/script/function.sh  && install_packages_macos

      - name: Create whl file for MacOS 10.15
        run: . .github/workflows/script/function.sh && build_package_macos
      - name: Check package information
        run: source ~/.bash_profile && . .github/workflows/script/function.sh \
          && check_package_macos
      - name: Install package
        run: |
          . .github/workflows/script/function.sh && source ~/.bash_profile
          install_client_macos
      - name: Start Griddb Server
        run: docker run -t -d --net=host --name griddb -e GRIDDB_CLUSTER_NAME=${GRIDDB_SERVER_NAME} ${GRIDDB_IMAGE} #eval "$(docker-machine env default)"

      - name: Run sample
        run: |
          source ~/.bash_profile && . .github/workflows/script/function.sh
          master_node_ip_address=$(ipconfig getifaddr en0)
          master_node_port=10001
          run_sample ${master_node_ip_address} ${master_node_port} ${GRIDDB_SERVER_NAME} ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}

      - name: Uninstall package
        run: . .github/workflows/script/function.sh && source ~/.bash_profile
          uninstall_package ${PACKAGE_NAME}
      - name: Upload whl file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/griddb_python-*.whl
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

