name: Create package on release

on: create

env:
  GRIDDB_SERVER_NAME: "griddb"
  GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
  GRIDDB_NOTIFICATION_PORT: "31999"
  GRIDDB_USERNAME: "admin"
  GRIDDB_PASSWORD: "admin"
  GRIDDB_PACKAGE_NAME: "griddb-c-client"
  GRIDDB_C_CLIENT_VERSION: ""
  GRIDDB_SERVER_VERSION: "" 

jobs:
  release_package:
    name: Create and release ${{ matrix.file_type }} file for ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: Ubuntu
            docker_file: .github/dockerfiles/Dockerfile-ubuntu18.04
            docker_image: ubuntu
            container_name: ubuntu_container
            package_path: dist/griddb_python-*.whl

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: docker build -t ${{ matrix.docker_image }} -f ${{ matrix.docker_file }} .
      - name: Run Docker Image
        run: docker run --name ${{ matrix.container_name }} -it -d -v `pwd`:/python_client ${{ matrix.docker_image }}
      - name: Create whl file for ${{ matrix.os }}
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec "cd python_client/ && . .github/workflows/script/function.sh \
             && build_package"
      - name: Check package information
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec "cd python_client/ && . .github/workflows/script/function.sh \
             && check_package"
      - name: Install package
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec "cd python_client/ && . .github/workflows/script/function.sh && install_client"
      - name: Config GridDB server
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec "cd python_client/ && . .github/workflows/script/function.sh \
             && config_griddb ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD} ${GRIDDB_SERVER_NAME}"
      - name: Start server
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec "cd python_client/ && . .github/workflows/script/function.sh \
             && start_griddb ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD} ${GRIDDB_SERVER_NAME}"
      - name: Run sample
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec "cd python_client/ && . .github/workflows/script/function.sh \
             && run_sample ${GRIDDB_NOTIFICATION_ADDRESS} ${GRIDDB_NOTIFICATION_PORT} ${GRIDDB_SERVER_NAME} ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}"
      - name: Stop server
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec "cd python_client/ && . .github/workflows/script/function.sh \
             && stop_griddb ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}"
      - name: Uninstall package
        run: docker exec ${{ matrix.container_name }} /bin/bash -xec "cd python_client/ && . .github/workflows/script/function.sh \
             && uninstall_package ${GRIDDB_PACKAGE_NAME} ${{ matrix.os }}"
      - name: Upload whl file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.package_path }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  release_package_on_macos_10_15:
    name: Create and release whl file for MacOS 10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment for MacOS 10.15
        run: . .github/workflows/script/function.sh \
             && install_packages_macos
      - name: Create whl file for MacOS 10.15
        run: . .github/workflows/script/function.sh \
             && build_package_macos
      - name: Check package information
        run: source ~/.bash_profile && . .github/workflows/script/function.sh \
             && check_package_macos
      - name: Install package
        run: . .github/workflows/script/function.sh && source ~/.bash_profile && install_client_macos
      - name: Pull Griddb Server image
        run: eval "$(docker-machine env default)" && docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && docker pull griddb/griddb:latest
      - name: Start Griddb Server
        run: |
          eval "$(docker-machine env default)"
          docker run -t -d --name griddb --network="host" -e GRIDDB_CLUSTER_NAME=${GRIDDB_SERVER_NAME} griddb/griddb
          docker exec -i griddb /bin/bash -c "gs_stat -u admin/admin"
          python sample/sample1.py 239.0.0.1 31999 griddb admin admin
      - name: Upload whl file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/griddb_python-*.whl
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Run sample
        run: source ~/.bash_profile && . .github/workflows/script/function.sh \
             && run_sample_macos ${GRIDDB_NOTIFICATION_ADDRESS} ${GRIDDB_NOTIFICATION_PORT} ${GRIDDB_SERVER_NAME} ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}
